# Site settings
course_name: IoT Operating Systems
course_description: "This course will explore the fundations of modern Real-time operating systems from the programmer's perspective. Topics include structure of real-­time embedded systems, interrupts, concurrent task synchronization and communication, inter-process interface and multitasking, sharing resources, schedulability and reliability. The course will provide a particular emphasis on predictable scheduling algorithms and provide the basic methodologies for designing predictable computing systems useful in supporting time critical IoT systems. The course also discuss popular open-source FreRTOS to identify the benefits and weaknesses in deciding whether or not to adopt more traditional, less powerful, techniques for a project."
course_semester: 

baseurl: "/ecs6264" # the subpath of your site, e.g. /blog/
url: "https://qiriro.com" # the base hostname & protocol for your site
# schoolname: "University of Rwanda"
# schoolurl: ""
twitter_username: nkuzito 

address: |
    Kizito NKURIKIYEYEZU, Ph.D.
    http://qiriro.com/

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: UA-255547804

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
